### ISSUE TITLE
check for/warn about field group lists with uneven number of values across fields

### ISSUE THREAD

**Issue by kspurgin** [collectionspace/cspace-converter#167]
Converter tool code currently, in general, seems to make the assumption that in a repeatable grouping of fields, that there are equal numbers of values given each field. For example: 

name: name1; name2; name3
nametype: type1;;type3

Depending on how the CSV data is being compiled/generated, it could be really fiddly and error prone to get this right in the CSV!

I did not find anything in the converter tool code that would detect and emit a warning about CSV data like: 

name: name1; name2; name3
nametype: type1;type3

I believe it will just silently assign type 3 to name 2 and not assign a type to name 3. This behavior will quietly introduce errors that would be really difficult to catch. 

In the branch I'm currently working on, I've added [a method to check for this issue](https://github.com/collectionspace/cspace-converter/blob/1a752f8d657d6615efedebcd361b680047f00269/lib/collectionspace/converter/default/record.rb#L83).

Need feedback from @meganforbes on desired behavior if the converter detects uneven number of values for a field group. 

My opinion is that 

- the converter tool should process the data as it currently knows how
- the UI should clearly warn that there were issues in the source data that potentially resulted in data-conversion problems, and point the user to a place where they can see the details: field(s) + row(s) affected. 

Will need to discuss with @mark-cooper how to implement desired behavior. After that is decided, we may want to ask DDD to add the check/warn method in all places in the code where this is a potential issue.

**Comment by meganforbes** [comment]
+1 to your suggestion - process data, show issue with uneven number of values.
