### ISSUE TITLE
Fix dependence on non-required field values for iteratively populating fieldGroups

### ISSUE THREAD

**Issue by kspurgin** [collectionspace/cspace-converter#169]
For instance: https://github.com/collectionspace/cspace-converter/blob/a833bbb26831d615c87c764615e3350c3a0a1533/lib/collectionspace/converter/anthro/osteology.rb#L64-L78

`osteoAgeEstimateVerbatim` is not a required field. Other fields in the `osteoAgeEstimate` field may be present and need to be set when `osteoAgeEstimateVerbatim` has not been populated, or that column has been removed from the data being imported because the client doesn't need it. 

This code fails to import any data in this group if there is no data in for `osteoAgeEstimateVerbatim`

This problem exists throughout the cspace-converter code, and it should be fixed across the board. 

However, it's this part of the Osteology procedure module that is causing a problem importing client data now. It should be fixed first. (Mark cannot review/merge it until January 2 or after)

**Comment by kspurgin** [comment]
I added new Osteology sample data to test with in branch: [i169-safer-field-group-iteration](https://github.com/collectionspace/cspace-converter/tree/i169-safer-field-group-iteration)

[This file](https://github.com/collectionspace/cspace-converter/blob/i169-safer-field-group-iteration/data/anthro/osteology_anthro_sparse1.csv) is the situation with Osteology data we need to load now. The client has NO data in the column; the column isn't even there.

[This file](https://github.com/collectionspace/cspace-converter/blob/i169-safer-field-group-iteration/data/anthro/osteology_anthro_sparse2.csv) shows how real life client may be messy and inconsistent.

Clients should be able to leave a cell blank if there is no data and have the rest of the row treated properly. (row 3)

Some clients may be able to output what you see in row 4, which should also work. (But it seems unreasonable to expect clients to provide ' ; ' when there's no value)

Row 5 should work, assigning the verbatim value only to the 2nd group.

Row 6 is inherently problematic (follow [#167] to see how handling for this develops), but for now, the best behavior we can expect is for "late twenties" to be assigned to the first group and nothing assigned to the second group.

**Comment by kspurgin** [comment]
@Paulmulonzia -- I have fixed this issue for the missing osteoAgeEstimateVerbatim in the anthro/osteo module. 

I would like to pass this issue to you to work on refactoring the rest of the places in the code where we build a field group iteratively on a field that may not be populated. 

This is lower-priority work, because it is refactoring the things that are not currently blocking work we need to do. Please wait until @mark-cooper is back (on/after January 2) to consult with him on priorities/needs. 

However, I'm letting you know about it now, so any high-priority work you may be working on can avoid using this problematic pattern. Thanks!

You can look at how I fixed this in osteology.rb to find the pattern and new CSDR method for this.

**Comment by kspurgin** [comment]
The branch in #170 is identical to the branch in #160, so I'm going to get rid of #170.

**Comment by Paulmulonzia** [comment]
Hi @kspurgin,

Thanks for the update. 

I tried applying the fix but got the error below:

"import_message": "undefined method `add_group_list_with_structured_date' for CollectionSpace::Tools::XML:Class",

![image](https://user-images.githubusercontent.com/34029747/71673745-9cf10780-2d8a-11ea-9c97-0deb4f223af2.png)

**Comment by kspurgin** [comment]
Hi @Paulmulonzia -- I think the pull request needs to be reviewed by Mark and merged into the master branch before using it like that will work (?).

 Until then,`add_group_list_with_structured_date` is only defined in [this branch](https://github.com/collectionspace/cspace-converter/tree/i157-anthro-collobject), so if you aren't working in that branch, you'll get a message that method (and others) are not defined. 

Mark may find some other issues in what I did in this branch and maybe want to change some things, so I would suggest waiting until it's accepted and merged to do much work based on this if you can. I believe he is back early next week.

**Comment by Paulmulonzia** [comment]
Hi @kspurgin,

Sure, that sounds good. 

Thanks.
