### ISSUE TITLE
Inconsistent conversion of unstructured date data

### ISSUE THREAD

**Issue by kspurgin** [collectionspace/cspace-converter#175]
I think this may be something to handle in the Cspace application, not the converter tool, but perhaps not. 

We have this widget in the UI that just opens a simple calendar and lets you select a day.
![image](https://user-images.githubusercontent.com/450570/72386841-2809c000-36f0-11ea-9e42-a28806fa49b9.png)

In anthro collection object/annotationDate, the result of entering or choosing a date is: 
`<annotationDate>2019-12-19</annotationDate>`

In exhibition/venueOpeningDate and venueClosingDate, the result of the same UI widget is: 
`<venueOpeningDate>2000-01-01T00:00:00.000Z</venueOpeningDate>
<venueClosingDate>2000-02-01T00:00:00.000Z</venueClosingDate>`

Does the converter tool need to be able to handle another date format? We currently have structured_date and unstructured_date (which handles that annotationDate format). We'd need to add something like unstructured_date_only_time_stamp (not sure if there's anywhere we are actually recording timestamps that shouldn't be T00:00:00.000Z by default).

Or should the application be updated to just record these fields as dates since that's the level of granularity the UI allows you to input?

**Comment by kspurgin** [comment]
@mark-cooper -- thoughts?

**Comment by mark-cooper** [comment]
@kspurgin not another variation! 😖 
Would it work to just call the date parser directly (not going through a helper)? Something like:

```ruby
CSXML.add xml, 'annotationDate', CSDTP.parse(attributes['annotationdate']).display_date
CSXML.add xml, 'venueOpeningDate', CSDTP.parse(attributes['venueopeningdate']).earliest_scalar
CSXML.add xml, 'venueClosingDate', CSDTP.parse(attributes['venueclosingdate']).earliest_scalar
```

We can ask Ray / Megan about the cspace side of things tomorrow ... I don't think I've come across a parsed date outside of a date group before so I'm not sure what the deal is there.

**Comment by kspurgin** [comment]
Unfortunately I don't think we can send the data through the date parser directly because these occur in various multivalue/nesting configurations that get handled via the helpers which rely on apply_transforms. 

Bleh. 

Fairly simple to write the variation, but it conceptually annoys me that we should have to when the UI doesn't allow to to enter a time value for these at all, so the extra specificity is meaningless. 

Unfortunately it is starting to look like maybe there are more like this than like <annotationDate>. All the dates in the condition check procedure have the all-zero timestamp.
