### ISSUE TITLE
Converter profile for CORE exhibition

### ISSUE THREAD

**Issue by mark-cooper** [collectionspace/cspace-converter#183]

**Comment by Paulmulonzia** [comment]
Hi @kspurgin,

All fields updated on exhibition.

Pending item: add_group_list_with_structured_date not accepting two date fields(galleryRotationStartDateGroup and galleryRotationEndDateGroup), I tried using the two date fields as an array as well which also didn't work:

https://github.com/collectionspace/cspace-converter/blob/33331f81f6a6a977fc259ef544de99d2e711e192/lib/collectionspace/converter/core/exhibition.rb#L97-L107

Here's the spec file:

https://github.com/collectionspace/cspace-converter/blob/33331f81f6a6a977fc259ef544de99d2e711e192/spec/collectionspace/converter/core/exhibition_spec.rb#L27-L30

Thanks.

**Comment by Paulmulonzia** [comment]
Records with null values on both **exhibitionPersonOrganization** and **exhibitionPersonPerson** (part of nested grouplist) e.g. Record 005 and 013 failing on import with the error message: "undefined method `split' for nil:NilClass"

**Comment by kspurgin** [comment]
@Paulmulonzia  RE: add_group_list_with_structured_date not accepting two date fields

Nope, it wouldn't accept them because it was written assuming there was only one. 

I will update it to accept/handle an array of date fields to treat as groups, but I will not be able to work on that until late Tuesday at the earliest.

**Comment by Paulmulonzia** [comment]
Sounds good, thanks @kspurgin.

**Comment by Paulmulonzia** [comment]
Hi @kspurgin,

The transform function fails to match the second field of **exhibitionPerson** which is multivalued. The first field test is successful.

https://github.com/collectionspace/cspace-converter/blob/98a60a0ee212353817cb2d043e451265998f5f42/spec/collectionspace/converter/core/exhibition_spec.rb#L26

Here's the error message:

![image](https://user-images.githubusercontent.com/34029747/74035844-1f916600-49cc-11ea-8b92-d2d3a27ecc1f.png)

**Comment by kspurgin** [comment]
Paul, can you please create an issue [here](https://github.com/collectionspace/cspace-converter/issues) for this problem and assign it to me. 

If you are unable to create issues, let me know.

**Comment by Paulmulonzia** [comment]
Sure, here's the link: https://github.com/collectionspace/cspace-converter/issues/202
