### ISSUE TITLE
Null values in all multi-authority columns croaks

### ISSUE THREAD

**Issue by kspurgin** [collectionspace/cspace-converter#191]
Paul reported [here](https://github.com/collectionspace/cspace-converter/issues/183#issuecomment-578713382). Blocks #183 

> Records with null values on both exhibitionPersonOrganization and exhibitionPersonPerson (part of nested grouplist) e.g. Record 005 and 013 failing on import with the error message: "undefined method `split' for nil:NilClass"

**Comment by kspurgin** [comment]
So, in testing this, I found it is not simply null values on both exhibitionPersonOrganization and exhibitionPersonPerson causing the problem. 

I added a minimal record with null values on both exhibitionPersonOrganization and exhibitionPersonPerson to the sample data and I get no errors when testing conversion of that row.

**Comment by kspurgin** [comment]
The problem was instead where some of the fields within the nested workingGroupList are populated, but one or more of the child fields are not present.

**Comment by kspurgin** [comment]
@Paulmulonzia - this is fixed. I merged my changes into the `DDD-Core-Exhibition_07-01-2020` branch

**Comment by Paulmulonzia** [comment]
Thanks @kspurgin
