### ISSUE TITLE
Look into creating/improving method for add_list

### ISSUE THREAD

**Issue by kspurgin** [collectionspace/cspace-converter#196]
From Paul: "Hi @kspurgin, is it possible to have something similar to CSXML.add_single_level_group_list for add_list.

Here's an instance I think it would be useful:

https://github.com/collectionspace/cspace-converter/blob/DDD-Core-cataloging_27-01-2020/lib/collectionspace/converter/core/collectionobject.rb#L132-L138"

**Comment by kspurgin** [comment]
@Paulmulonzia - `add_single_level_group_list` already can do this. We don't need a separate `add_list` function. 

Prefer not to use `add_list` going forward. I hope to refactor existing code sometime soon to remove it altogether (because its presence is confusing).

See my comment here: https://github.com/collectionspace/cspace-converter/pull/200#discussion_r375519845

**Comment by Paulmulonzia** [comment]
Well noted, thank you @kspurgin.
