### ISSUE TITLE
Create a rake task for transferring ALL authority records

### ISSUE THREAD

**Issue by remillet** [collectionspace/cspace-converter#25]
Create a rake task for transferring ALL authority records to CollectionSpace.  -for example,

`./bin/rake remote:action:transfer[AUTHORITIES, all]`

Mark, 4:45 PM

> a hacky way would be to get the auth types from the "profile" _config.rb file, loop those: "./bin/rake remote:action:transfer[$type,all]" ... probs more trouble than worth

**Comment by mark-cooper** [comment]
Converter modules now declare which authorities they support:

https://github.com/lyrasis/cspace-converter/blob/master/lib/collectionspace/converter/core/_config.rb#L13

So this should be easily doable.
