### ISSUE TITLE
Fields Mapped under wrong namespace

### ISSUE THREAD

**Issue by Paulmulonzia** [collectionspace/cspace-converter#269]
Hi @mark-cooper, I have an issue when mapping the nagpra claims profile whereby fields under the namespace **ns2:claims_common** are being mapped in **ns2:claims_nagpra**. This is despite the fields being properly mapped in the converter as shown [here](https://github.com/collectionspace/cspace-converter/blob/DDD-Anthro-Nagpra_16-04-2020/lib/collectionspace/converter/anthro/nagpra.rb)
 The xml structure therefore ends being different from what is expected by cspace and transfer job fails.

![image](https://user-images.githubusercontent.com/34029747/79621578-92316700-811c-11ea-8633-c07fe4c75286.png)

The issue only applies to grouplist fields. Pairs have been correctly mapped under **ns2:claims_common**

Thanks

**Comment by Paulmulonzia** [comment]
Blocks https://github.com/collectionspace/cspace-converter/issues/268

**Comment by mark-cooper** [comment]
Hi @Paulmulonzia 

Can you clarify which field specifically is a problem? I don't think I can spot a problem with fields mapping to the wrong place.

The error message is saying that it doesn't accept "nagpraClaimInitialResponseNote", which is part of the mapping for "claims_nagpra", which appears to set by:

https://github.com/collectionspace/cspace-converter/blob/DDD-Anthro-Nagpra_16-04-2020/lib/collectionspace/converter/anthro/nagpra.rb#L112-L126

Are you sure "nagpraClaimInitialResponseNote" is a valid field? Is it in the XML that comes from cspace?

**Comment by Paulmulonzia** [comment]
Yes nagpraClaimInitialResponseNote is available in the xml, here's the fixture [file](https://github.com/collectionspace/cspace-converter/blob/DDD-Anthro-Nagpra_16-04-2020/spec/fixtures/files/anthro_nagpra.xml#L139)

The affected fields are all fields under **[claimantGroupList](https://github.com/collectionspace/cspace-converter/blob/DDD-Anthro-Nagpra_16-04-2020/spec/fixtures/files/anthro_nagpra.xml#L231-L242)** and **[claimReceivedGroupList](https://github.com/collectionspace/cspace-converter/blob/DDD-Anthro-Nagpra_16-04-2020/spec/fixtures/files/anthro_nagpra.xml#L221-L230)**.

Both grouplists fall under **ns2:claims_common**.

Thanks.

**Comment by Paulmulonzia** [comment]
Only the field **claimNumber** is being created in **claims_common**. The two grouplists (claimantGroupList and claimReceivedGroupList.) are somehow being created in **claims_nagpra**.

 
![image](https://user-images.githubusercontent.com/34029747/79623604-e2f98d80-8125-11ea-994d-f40834757513.png)

**Comment by mark-cooper** [comment]
For the "nagpraClaimInitialResponseNote" error see:

https://github.com/collectionspace/cspace-converter/blob/DDD-Anthro-Nagpra_16-04-2020/lib/collectionspace/converter/anthro/nagpra.rb#L175

"nagpraClaimInitialResponseNote" should be "nagpraClaimNatlRespNote"

I was then able to transfer and delete the record from anthro.dev.

I have to wrap up for the day so I can't get to the others right now. Because they don't appear at all I guess there's a nil value being passed somewhere so the group isn't being generated or something like that. I'd start out by trying one data attribute at a time and to see if there's a particular field that's a problem.

**Comment by Paulmulonzia** [comment]
Thanks @mark-cooper, the grouplists weren't being created due to small typo. Everything works fine now.
