### ISSUE TITLE
PublicArt Import Error: no implicit conversion of String into Integer

### ISSUE THREAD

**Issue by Paulmulonzia** [collectionspace/cspace-converter#277]
Hi @mark-cooper @kspurgin ,

I am encountering the following error when importing Location/Movement/Inventory data for the PublicArt converter module:

![image](https://user-images.githubusercontent.com/34029747/81275971-0f386800-905b-11ea-81fb-cb5a18bb85e5.png)

**Comment by kspurgin** [comment]
You're getting this error on this branch? https://github.com/collectionspace/cspace-converter/tree/DDD-PublicArt-LMI_04-05-2020

**Comment by Paulmulonzia** [comment]
Yes, that's the one

**Comment by kspurgin** [comment]
Ok, I'm in the middle of testing something else in the tool, but I'll look at this next! Thanks.

**Comment by Paulmulonzia** [comment]
Great, thank you.

**Comment by kspurgin** [comment]
I believe I have fixed this by updating the config.yml Authorities section under movement to match the current format we are using for core. I pushed the change to the branch.

**Comment by Paulmulonzia** [comment]
Works well now, thanks.
