### ISSUE TITLE
Xpath Failure: doc was empty.

### ISSUE THREAD

**Issue by Paulmulonzia** [collectionspace/cspace-converter#292]
I am getting an error when running spec tests on valuation control for public arts. The error message is as shown below:

` Failure/Error: expect(doc_text).not_to be_empty, -> { "Xpath for doc was empty: #{xpath}" }
       Xpath for doc was empty: /document/valuationcontrols_common/valuationcontrolRefNumber
`

![image](https://user-images.githubusercontent.com/34029747/81529265-32b72780-9367-11ea-89cb-9fb23f05f42a.png)

This happens despite the fixture file field **valuationcontrolRefNumber** not being empty as implied by the error message. Sample data too is also not null.

Affects #291

Branch: https://github.com/collectionspace/cspace-converter/tree/DDD-PublicArt-Valuation_04-05-2020

**Comment by kspurgin** [comment]
This is really weird. I'm getting the same error, and it doesn't make any sense yet. Looking further...

**Comment by kspurgin** [comment]
Anthro tests are passing, so I want to compare how those are working to how this one is working. 

I added `binding.pry` before [this line](https://github.com/collectionspace/cspace-converter/blob/3b102ef2045f1ab6a1be230c5476ad364b390699/spec/collectionspace/converter/anthro/collectionobject_spec.rb#L141) in anthro collectionobject spec, to get the shortest (# only) document.

```
[1] pry(#<RSpec::ExampleGroups::CollectionSpaceConverterAnthroAnthroCollectionObject::MapNagpra::SampleDataRow7ObjectNumberOnly>)> pp(doc)
#(Document:0x3fd8ead6cf60 {
  name = "document",
  children = [
    #(Element:0x3fd8ead6c6a0 {
      name = "document",
      attributes = [
        #(Attr:0x3fd8ead6c240 { name = "name", value = "collectionobjects" })],
      children = [
        #(Text "\n" + "  "),
        #(Element:0x3fd8ead70a98 {
          name = "collectionobjects_common",
          children = [
            #(Text "\n" + "    "),
            #(Element:0x3fd9126d76a0 {
              name = "objectNumber",
              children = [ #(Text "20CS.001.0010")]
              }),
            #(Text "\n" + "  ")]
          }),
        #(Text "\n")]
      })]
  })
```
I did the same thing in the publicart/valuation spec, on the minimally populated record, and when I `pp` in pry, I get: 

```
[1] pry(#<RSpec::ExampleGroups::CollectionSpaceConverterPublicArtPublicArtValuationControl::ForMinimallyPopulatedRecord>)> pp(doc)
#(Document:0x3fc7400a12d8 {
  name = "document",
  children = [
    #(Element:0x3fc75421d710 {
      name = "document",
      attributes = [
        #(Attr:0x3fc754228b38 { name = "name", value = "valuationcontrols" })],
      children = [
        #(Text "\n" + "  "),
        #(Element:0x3fc7542688f0 {
          name = "valuationcontrols_common",
          namespace = #(Namespace:0x3fc75426de04 {
            prefix = "ns2",
            href = "http://collectionspace.org/services/valuationcontrol"
            }),
          children = [
            #(Text "\n" + "    "),
            #(Element:0x3fc754281a58 {
              name = "valuationcontrolRefNumber",
              children = [ #(Text "VAL2000.021")]
              }),
            #(Text "\n" + "  ")]
          }),
        #(Text "\n")]
      })]
  })
```

What I notice here is the `valuationcontrols_common` element  has a namespace defined, whereas the `collectionobjects_common` in anthro does not. 

I remember something from a previous project on having to format xpath for namespaces differently, so I bet this is the issue... Let me try to figure out *why* that namespace is getting defined that way. First I will check in core/valuationcontrol and see what's happening there (its tests are not failing):

```
[1] pry(#<RSpec::ExampleGroups::CollectionSpaceConverterCoreCoreValuationControl::ForMinimallyPopulatedRecord>)> pp(doc)
#(Document:0x3fbf81322c94 {
  name = "document",
  children = [
    #(Element:0x3fbf81327974 {
      name = "document",
      attributes = [
        #(Attr:0x3fbf813273d4 { name = "name", value = "valuationcontrols" })],
      children = [
        #(Text "\n" + "  "),
        #(Element:0x3fbf8132bb64 {
          name = "valuationcontrols_common",
          namespace = #(Namespace:0x3fbf8132b790 {
            prefix = "ns2",
            href = "http://collectionspace.org/services/valuationcontrol"
            }),
          children = [
            #(Text "\n" + "    "),
            #(Element:0x3fbf8132f9a8 {
              name = "valuationcontrolRefNumber",
              children = [ #(Text "VAL2000.021")]
              }),
            #(Text "\n" + "  ")]
          }),
        #(Text "\n")]
      })]
  })
```

Namespace **is** being defined. 

The difference here (and reason tests pass) is we are using `*` in the xpaths. 

Specifying the `valuationcontrols_common` level of the xpath explictly returns empty array: 
```[2] pry(#<RSpec::ExampleGroups::CollectionSpaceConverterCoreCoreValuationControl::ForMinimallyPopulatedRecord>)> doc.xpath('document/valuationcontrols_common/valuationcontrolRefNumber')
=> []
```

Using `*` to specify whatever returns the expected element, so the test passes: 
[3] pry(#<RSpec::ExampleGroups::CollectionSpaceConverterCoreCoreValuationControl::ForMinimallyPopulatedRecord>)> doc.xpath('document/*/valuationcontrolRefNumber')
=> [#<Nokogiri::XML::Element:0x3fbf8132f9a8 name="valuationcontrolRefNumber" children=[#<Nokogiri::XML::Text:0x3fbf8132eabc "VAL2000.021">]>]

There's a command to remove all namespaces from all nodes in the document, so I try that:

```
[4] pry(#<RSpec::ExampleGroups::CollectionSpaceConverterCoreCoreValuationControl::ForMinimallyPopulatedRecord>)> no_namespace_doc = doc.remove_namespaces!
=> #(Document:0x3fbf81322c94 {
  name = "document",
  children = [
    #(Element:0x3fbf81327974 {
      name = "document",
      attributes = [ #(Attr:0x3fbf813273d4 { name = "name", value = "valuationcontrols" })],
      children = [
        #(Text "\n  "),
        #(Element:0x3fbf8132bb64 { name = "valuationcontrols_common", children = [ #(Text "\n    "), #(Element:0x3fbf8132f9a8 { name = "valuationcontrolRefNumber", children = [ #(Text "VAL2000.021")] }), #(Text "\n  ")] }),
        #(Text "\n")]
      })]
  })
```

The namespace declaration **was** removed.

Now I test my full/explicitly stated xpath and it works: 

```
[5] pry(#<RSpec::ExampleGroups::CollectionSpaceConverterCoreCoreValuationControl::ForMinimallyPopulatedRecord>)> no_namespace_doc.xpath('document/valuationcontrols_common/valuationcontrolRefNumber')
=> [#<Nokogiri::XML::Element:0x3fbf8132f9a8 name="valuationcontrolRefNumber" children=[#<Nokogiri::XML::Text:0x3fbf8132eabc "VAL2000.021">]>]
```

This gives me a solution. I want to test it and commit it, and then I will explain what I did.

**Comment by kspurgin** [comment]
My solution was going to be: add `remove_namespaces!` to the `get_doc` spec helper method, but [it is already there](https://github.com/collectionspace/cspace-converter/blob/75f4a58566530b13aa9db0eca34bbb5d7038605e/spec/helpers.rb#L29)!

So the problem for this test is that it is setting up the `let(:doc)` without using that helper method, so the namespaces weren't removed. 

I just committed a change to the valuation_spec making it use the method. That fixed the problem.

**Comment by kspurgin** [comment]
This brings my attention to another issue with the converter for publicart/valuation, so please pause until I've explained. I will do that explanation elsewhere since it isn't related to this issue.
