### ISSUE TITLE
Update converter profile: Acquisition - Public Art

### ISSUE THREAD

**Issue by Paulmulonzia** [collectionspace/cspace-converter#301]

**Comment by kspurgin** [comment]
@Paulmulonzia -- when one of these issues is ready for code review, would you be willing to link it to the relevant pull request over on the right sidebar?

That'll help me keep track of work easier, and also merge of the PR will handle closing the issue. 

This can actually be done at any point after both the issue and PR are created. Thanks!

**Comment by Paulmulonzia** [comment]
Sure, I'll be doing that.

**Comment by kspurgin** [comment]
@Paulmulonzia - I've created PR #304 to allow comparison of some more extensive changes I ended up making. Once you have had a chance to review all the comments in that code, and we have discussed any questions you have, we can merge those changes into the branch used for your PR #302 , and then merge 302 into master.

**Comment by kspurgin** [comment]
@Paulmulonzia - check out the following for new rspec pattern documentation: https://github.com/collectionspace/cspace-converter/wiki/Methods-and-patterns-for-Rspec-tests

It refers to code in `test-helpers-and-bugfix` branch, where I am making sure specs are consistent with new patterns documented there.
