### ISSUE TITLE
Create converter profile - Distribution - Botanical Gardens

### ISSUE THREAD

**Issue by Paulmulonzia** [collectionspace/cspace-converter#317]
Hi @kspurgin,

Seems the Botgardens config is not available [here](https://github.com/collectionspace/cspace-converter/tree/master/docs/test)

I am trying to figure out the CSPACE_CONVERTER_BASE_URI so that I can feed in sample data.

Thanks.

**Comment by kspurgin** [comment]
@Paulmulonzia - should be https://botgarden.dev.collectionspace.org/cspace-services

basically if you look at [this](https://github.com/collectionspace/cspace-converter/blob/master/docs/test/ANTHRO.md) and replace anthro with botgarden, I think that should work.

**Comment by Paulmulonzia** [comment]
Thanks @kspurgin, I was using botgardens instead that's why I wasn't able to access the URL.
