### ISSUE TITLE
Converter profile for LoansOut_Core_All

### ISSUE THREAD

**Issue by mark-cooper** [collectionspace/cspace-converter#88]
Branch: DDD-loansout-core

Mapping

https://github.com/lyrasis/cspace-converter/blob/master/lib/collectionspace/converter/core/loanout.rb

Data

https://github.com/lyrasis/cspace-converter/blob/master/data/core/loansout_core_all.csv

Config: use "core"

https://github.com/lyrasis/cspace-converter/blob/master/DEV.md#core

Start by manually creating a record in cspace using first row of sample data. Export the XML then delete the record from cspace. Make a PR including the reference XML (spec/fixtures/files/) and initial mapping spec (spec/collectionspace/converter/core/). From the converter you can use: bundle exec rake remote:get[acquisitions/$csid] to get the XML.

Implement fields not covered in mapping currently.

**Comment by mark-cooper** [comment]
@Paulmulonzia I fixed a few (pretty small) issues in this PR:

https://github.com/collectionspace/cspace-converter/pull/86

Bring yourself up to date with master and start a new branch for ongoing work and you should be all set.

Couple of notes:

1. In the specs for testing vocabularys the trick to overcome not having a local cache is: CSURN.parse(text)[:label].downcase

https://github.com/collectionspace/cspace-converter/blob/master/spec/collectionspace/converter/core/objectexit_spec.rb#L30

2. Some dates will still give issues, including US formatted dates (i.e. 11/11/2001) from the csv, just comment those out for now:

https://github.com/collectionspace/cspace-converter/blob/master/spec/collectionspace/converter/core/objectexit_spec.rb#L19

**Comment by Paulmulonzia** [comment]
Thanks for the update @mark-cooper.

I uncommented the rest of the fields and import to cspace works perfectly.

I have pushed the new branch.

**Comment by mark-cooper** [comment]
https://github.com/collectionspace/cspace-converter/pull/94

**Comment by meganforbes** [comment]
Loan status fields not accepting multiple values. Sample data updated to include multiple values in line 1. Also two new fields added to record since data dictionary was first created - add to profile?
[Loan Out Sample Data.xlsx](https://github.com/collectionspace/cspace-converter/files/4099695/Loan.Out.Sample.Data.xlsx)

**Comment by Paulmulonzia** [comment]
@meganforbes, Loan status fields updated. I've made a pull request with the new changes.

**Comment by meganforbes** [comment]
Two fields missing, loan status group and loan status individual.

**Comment by Paulmulonzia** [comment]
Hi @meganforbes, 

Missing fields added, **borrowerPerson** also added to converter and sample data to allow support for both organization and person authorities for the field **borrower**.

Thanks.

**Comment by meganforbes** [comment]
QA complete.
