### ISSUE TITLE
Converter profile for ObjectExit_Core_All

### ISSUE THREAD

**Issue by mark-cooper** [collectionspace/cspace-converter#89]
Branch: DDD-objectexit-core

Mapping

https://github.com/lyrasis/cspace-converter/blob/master/lib/collectionspace/converter/core/exit.rb

Data

https://github.com/lyrasis/cspace-converter/blob/master/data/core/objectexit_core_all.csv

Config: use "core"

https://github.com/lyrasis/cspace-converter/blob/master/DEV.md#core

Start by manually creating a record in cspace using first row of sample data. Export the XML then delete the record from cspace. Make a PR including the reference XML (spec/fixtures/files/) and initial mapping spec (spec/collectionspace/converter/core/). From the converter you can use: bundle exec rake remote:get[acquisitions/$csid] to get the XML.

Implement fields not covered in mapping currently.

**Comment by Paulmulonzia** [comment]
Hi @mark-cooper, 

I tested out import and all objects are successfully being imported to cspace. 

I have updated the vocab fields to use "[:label].downcase"  in the mapping spec and created a pull request with the new updates.

Pending issue is the "exitReason" field won't pick the value **return of loan** but **deaccession** and  **disposal** both import without any issues. I checked from the exported xml it appears as **returnofloan** 

<exitReason>returnofloan</exitReason>


therefore the data in this field shouldn't contain any whitespace for the import to work. Should I modify the sample data to be similar to what we have from the exported xml?

Thanks.

**Comment by mark-cooper** [comment]
"Should I modify the sample data to be similar to what we have from the exported xml?"

I believe yes. @meganforbes we discussed the issue with static list terms and decided that we'd "expect" the csv to contain valid data, right?

**Comment by mark-cooper** [comment]
For the record I updated the csv (returnofloan).

**Comment by Paulmulonzia** [comment]
Thank you @mark-cooper

**Comment by meganforbes** [comment]
Updated data sample attached. Field names updated to match current style (i.e. currentOwnerOrganization, currentOwnerPerson) for fields that point to multiple vocabs. 

Data not importing into exitDateGroup, other date fields appear fine.

[Object Exit Data Sample.xlsx](https://github.com/collectionspace/cspace-converter/files/4097984/Object.Exit.Data.Sample.xlsx)

**Comment by Paulmulonzia** [comment]
Thanks @meganforbes, looking into it.

@kspurgin, Please advice on how to transform structured dates for single fields (not in grouplist):

https://github.com/collectionspace/cspace-converter/blob/DDD-Core-conservation_08-01-2020/spec/fixtures/files/core_objectexit.xml#L20-L44

I've tried add_date_group(xml, field, date) and I am getting the error:

"undefined method `display_date' for \"exitdategroup\":String"

https://github.com/collectionspace/cspace-converter/blob/DDD-Core-ObjectExit_23-01-2020/lib/collectionspace/converter/core/exit.rb#L63

**Comment by kspurgin** [comment]
@Paulmulonzia -- I don't think the handling of structured dates for single fields (not in grouplist) has changed

My advice is: use the search function within the cspace-converter repo in Github to search for other uses of add_date_group

From looking just at the [search results page here](https://github.com/collectionspace/cspace-converter/search?q=add_date_group&unscoped_q=add_date_group) and your exit.rb code, it looks like you are passing in a string as the 3rd parameter, when you need to be passing in the function to parse the sample data date value into structured date data. 

So instead of: 
`CSXML::Helpers.add_date_group(xml, 'exitDate', 'exitdategroup')`
try
`CSXML::Helpers.add_date_group(xml, 'exitDate', CSDTP.parse(attributes['exitdategroup']))`

**Comment by Paulmulonzia** [comment]
Got it.

Thanks @kspurgin

**Comment by Paulmulonzia** [comment]
@meganforbes, exitDateGroup updated as well as the new field names.

**Comment by meganforbes** [comment]
Field missing (wasn't in original sample data set) - deaccessionApprovalIndividual. Updated data set attached here.
[sample_data_objectexit_core_all.xlsx](https://github.com/collectionspace/cspace-converter/files/4172941/sample_data_objectexit_core_all.xlsx)

**Comment by Paulmulonzia** [comment]
Added deaccessionApprovalIndividual and deaccessionApprovalNote.

**Comment by meganforbes** [comment]
QA complete.
