### ISSUE TITLE
Converter profile for LMI_Core_All

### ISSUE THREAD

**Issue by mark-cooper** [collectionspace/cspace-converter#90]
Mapping

https://github.com/lyrasis/cspace-converter/blob/master/lib/collectionspace/converter/core/movement.rb

Data

https://github.com/lyrasis/cspace-converter/blob/master/data/core/lmi_core_all.csv

Config: use "core"

https://github.com/lyrasis/cspace-converter/blob/master/DEV.md#core

Start by manually creating a record in cspace using first row of sample data. Export the XML then delete the record from cspace. Make a PR including the reference XML (spec/fixtures/files/) and initial mapping spec (spec/collectionspace/converter/core/). From the converter you can use: bundle exec rake remote:get[acquisitions/$csid] to get the XML.

Implement fields not covered in mapping currently.

**Comment by Paulmulonzia** [comment]
Hello @mark-cooper, "movement" is currently disabled under import profiles in the UI.

Thanks.

**Comment by mark-cooper** [comment]
@Paulmulonzia free free to enable it as part of the pull request. That's just adding adding `enabled: true` under movement like: https://github.com/collectionspace/cspace-converter/blob/master/lib/collectionspace/converter/core/config.yml#L23

**Comment by Paulmulonzia** [comment]
Thank you @mark-cooper.

Updated the mappings and spec.

**Comment by meganforbes** [comment]
Tool does not appear to be accepting multiple values in movementMethod or inventoryContact fields.

**Comment by meganforbes** [comment]
Updated sample data attached. Changes - added new columns using updated style for normalLocationStorage, normalLocationOrganization, currentLocationStorage, and currentLocationOrganization.

Added multi values to two multi valued fields noted above.
[LMI Sample Data.xlsx](https://github.com/collectionspace/cspace-converter/files/4099730/LMI.Sample.Data.xlsx)
