### ISSUE TITLE
Converter profile for Nomenclature_Core_All

### ISSUE THREAD

**Issue by mark-cooper** [collectionspace/cspace-converter#92]
Mapping

https://github.com/lyrasis/cspace-converter/blob/master/lib/collectionspace/converter/core/concept.rb

Data

https://github.com/lyrasis/cspace-converter/blob/master/data/core/authconcept_nomenclature_terms.csv

Config: use "core"

https://github.com/lyrasis/cspace-converter/blob/master/DEV.md#core

Start by manually creating a record in cspace using first row of sample data. Export the XML then delete the record from cspace. Make a PR including the reference XML (spec/fixtures/files/) and initial mapping spec (spec/collectionspace/converter/core/). From the converter you can use: bundle exec rake remote:get[acquisitions/$csid] to get the XML.

Implement fields not covered in mapping currently.

**Comment by kspurgin** [comment]
@mark-cooper I was going to assign this to myself but looks like I can't. Have I been added to the cspace github team?

**Comment by mark-cooper** [comment]
@kspurgin you're invited 😄
