### ISSUE TITLE
Converter profile for Acquisition_Core_All

### ISSUE THREAD

**Issue by mark-cooper** [collectionspace/cspace-converter#97]
Mapping

https://github.com/lyrasis/cspace-converter/blob/master/lib/collectionspace/converter/core/acquisition.rb

Data

https://github.com/lyrasis/cspace-converter/blob/master/data/core/acquisition_core_all.csv

Config: use "core"

https://github.com/lyrasis/cspace-converter/blob/master/DEV.md#core

Start by manually creating a record in cspace using first row of sample data. Export the XML then delete the record from cspace. Make a PR including the reference XML (spec/fixtures/files/) and initial mapping spec (spec/collectionspace/converter/core/). From the converter you can use: bundle exec rake remote:get[acquisitions/$csid] to get the XML.

Attributes need to be updated i.e. acquisition_reference_number should be acquisitionreferencenumber

https://github.com/lyrasis/cspace-converter/blob/master/lib/collectionspace/converter/core/acquisition.rb#L15

Implement fields not covered in mapping currently.

**Comment by meganforbes** [comment]
1. Date fields not importing - accessionDateGroup in ok, but not acquisitionAuthorizerDate or acquisitionDateGroup. Sample data copied/pasted from link above.

**Comment by Paulmulonzia** [comment]
Hi @meganforbes,

I did test on core.dev and the date fields do seem to import:

https://core.dev.collectionspace.org/cspace/core/record/acquisition/32ee5d98-8455-49bd-91f6

![image](https://user-images.githubusercontent.com/34029747/71660006-b0847a00-2d5a-11ea-87fc-55260996817b.png)


@mark-cooper could there be a variation in different collectionspace domains in terms of the structure?

**Comment by meganforbes** [comment]
Looks like copy/pasting to Excel switched the date formats around from the CSV, so I fixed that and regular calendar dates import fine. Text strings, e.g. ca. 1945, not so much. @mark-cooper @kspurgin - thoughts?

**Comment by mark-cooper** [comment]
We can try and parse a date out a string like "ca. 1945" perhaps ... that sort of thing tends to be a rabbit hole though. Probably better if we just set the expectation that dates should be formatted correctly (in whatever documentation we are providing), otherwise they'll be skipped.

@meganforbes apart from the date issue is this one done?

**Comment by meganforbes** [comment]
Accession dates and Acquisition dates still not working, whether calendar or fuzzy (e.g. ca. 1945). Both need to work, we talked in our dev meeting about putting fuzzy dates in just as is, and then creating a data update that would run them through the parser after the fact.

**Comment by meganforbes** [comment]
Dates working.
